services:
  - type: web
    name: hvac-phone-agent
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: TELNYX_API_KEY
        sync: false
      - key: TELNYX_PHONE_NUMBER
        sync: false
      - key: VAPI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: WEBHOOK_BASE_URL
        sync: false